### ISSUE TITLE
How to use in VueJS

### ISSUE THREAD

**Issue by Alecyrus** [TitanSnow/markdown-it-v#2]
@TitanSnow Thanks for your awesome work. 

I install, import and use the markdown-it-v.

And there is a Vue component where contains a \<div\> element that is used for previewing the markdown rendered content. Like below:
``` html

<div id="markdown-body" ref="preview" class="preview-content">
    <Content :sdom="compiledMarkdown"/>
</div>
```

As you see, the compiledMarkdown is a sdom object.

```javascript
computed: {
        ...
        compiledMarkdown() {
            return this.mdit.render(this.code);
        }
    },
```
And I declare the Content Component:
```
let Content = Vue.component('Content', {
   props:["sdom"],
   render(h) {
        return h('div', null, this.sdom.toVue(h))
  }
})
```
Then I register the `Content` Component:
```
export default {
    ...
    component: {
        Content
    }

}
```

Then I got this error in console:
![image](https://user-images.githubusercontent.com/13865581/49324498-ba411a00-f569-11e8-8846-b73eb000f815.png)

And if I write: `return h('div', null, "Helloworld")`, that will be OK.

I notice this:
```javascript
renderToVDOM(h) {
    if (this.tagName === voidTag) {
      if (this.innerHTML != null) {
        throw new Error('`void` tag cannot contain innerHTML')  // Which means ??
      }
      return this.renderInnerVDOM(h)
    } else {
      return h(
        this.tagName,
        this.attrs,
        this.innerHTML,
        this.renderInnerVDOM(h),
      )
    }
  }
```

Could you please tell me what should I do to fix the problem?

**Comment by TitanSnow** [comment]
markdown-it-v doesn’t support HTML in markdown. It is because markdown-it places HTML tag and its content into different tokens.
